### ISSUE TITLE
Encountering RuntimeError in CUTEst Problem: INDEF

### ISSUE THREAD

**Issue by hjmshi** [hjmshi/PyTorch-LBFGS#4]
Dheevatsa, have you seen any errors of the following sort?
```
Traceback (most recent call last):
  File "lbfgs_tests.py", line 114, in <module>
    obj, grad, lr, backtracks, clos_evals, grad_evals, fail = optimizer.step(p, grad, options=options)
  File "../functions/LBFGS.py", line 720, in step
    self._add_update(t - t_prev, d)
  File "../functions/LBFGS.py", line 251, in _add_update
    p.data.add_(step_size, update[offset:offset + numel].view_as(p.data))
RuntimeError: Overflow when unpacking long
```
I observed this when testing the L-BFGS implementation on the CUTEst problems. I found this from a quick Google search: https://github.com/pytorch/pytorch/issues/6339, but my version of PyTorch is 0.4.1...do you know why this might occur?

**Comment by lwn66** [comment]
请问了解这个测试库的matlab接口吗？
